using System.Text.Json.Serialization;
using UsaEPay.NET.Converter;

namespace UsaEPay.NET.Models.Classes
{
    /// <summary>
    /// Response model for uploading a bulk transaction file.
    /// </summary>
    public class UsaEPayBulkTransactionUploadResponse : IUsaEPayResponse
    {
        /// <summary>
        /// Timestamp for transaction.
        /// </summary>
        [JsonConverter(typeof(USAePayStringToDateTimeOffsetConverter))]
        public DateTimeOffset? Timestamp { get; set; }

        /// <summary>
        /// Total possible transactions found in .csv file.
        /// </summary>
        [JsonPropertyName("lines")]
        public int Lines { get; set; }

        /// <summary>
        /// Number of lines detected within file which will attempt to process.
        /// </summary>
        [JsonPropertyName("transactions")]
        public int Transactions { get; set; }

        /// <summary>
        /// Number of lines that could not be accepted for processing due to incorrect formatting.
        /// </summary>
        [JsonPropertyName("errors")]
        public string[] Errors { get; set; }

        /// <summary>
        /// Number of duplicate files detected in past bulk transaction uploads.
        /// </summary>
        [JsonPropertyName("dupes")]
        public int Dupes { get; set; }

        /// <summary>
        /// Unique identifier for group of transactions generated by gateway.
        /// </summary>
        [JsonPropertyName("bulk_key")]
        public string BulkKey { get; set; }
    }

    /// <summary>
    /// Response model for retrieving the status of a bulk transaction file.
    /// </summary>
    public class UsaEPayBulkTransactionResponse : IUsaEPayResponse
    {
        /// <summary>
        /// Timestamp for transaction.
        /// </summary>
        [JsonConverter(typeof(USAePayStringToDateTimeOffsetConverter))]
        public DateTimeOffset? Timestamp { get; set; }

        /// <summary>
        /// Unique identifier for group of transactions generated by gateway.
        /// </summary>
        [JsonPropertyName("bulk_key")]
        public string BulkKey { get; set; }

        /// <summary>
        /// Date and time the file was uploaded.
        /// </summary>
        [JsonPropertyName("uploaded")]
        public string Uploaded { get; set; }

        /// <summary>
        /// Name of the file containing the transactions.
        /// </summary>
        [JsonPropertyName("filename")]
        public string Filename { get; set; }

        /// <summary>
        /// Current status of the bulk transaction upload.
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Number of total transactions uploaded.
        /// </summary>
        [JsonPropertyName("transactions")]
        public string Transactions { get; set; }

        /// <summary>
        /// Number of transactions left to process.
        /// </summary>
        [JsonPropertyName("remaining")]
        public string Remaining { get; set; }

        /// <summary>
        /// Number of approved transactions currently processed within the bulk transaction file.
        /// </summary>
        [JsonPropertyName("approved")]
        public string Approved { get; set; }

        /// <summary>
        /// Number of declined transactions currently processed within the bulk transaction file.
        /// </summary>
        [JsonPropertyName("declined")]
        public string Declined { get; set; }

        /// <summary>
        /// Number of errored transactions currently processed within the bulk transaction file.
        /// </summary>
        [JsonPropertyName("errors")]
        public string Errors { get; set; }
    }

    /// <summary>
    /// Response model for retrieving transactions from a bulk transaction file.
    /// </summary>
    public class UsaEPayBulkTransactionListResponse : IUsaEPayResponse
    {
        /// <summary>
        /// Timestamp for transaction.
        /// </summary>
        [JsonConverter(typeof(USAePayStringToDateTimeOffsetConverter))]
        public DateTimeOffset? Timestamp { get; set; }

        /// <summary>
        /// Object type. This will always be list.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// The maximum amount of transactions that will be included.
        /// </summary>
        [JsonPropertyName("limit")]
        [JsonConverter(typeof(ParseStringToLongConverter))]
        public long Limit { get; set; }

        /// <summary>
        /// The number of transactions skipped from the results.
        /// </summary>
        [JsonPropertyName("offset")]
        [JsonConverter(typeof(ParseStringToLongConverter))]
        public long Offset { get; set; }

        /// <summary>
        /// An array of transactions matching the search.
        /// </summary>
        [JsonPropertyName("data")]
        public UsaEPayResponse[] Data { get; set; }

        /// <summary>
        /// The total number of transactions in the file.
        /// </summary>
        [JsonPropertyName("total")]
        [JsonConverter(typeof(ParseStringToLongConverter))]
        public long Total { get; set; }
    }

    /// <summary>
    /// Response model for pause/resume bulk transaction operations.
    /// </summary>
    public class UsaEPayBulkTransactionActionResponse : IUsaEPayResponse
    {
        /// <summary>
        /// Timestamp for transaction.
        /// </summary>
        [JsonConverter(typeof(USAePayStringToDateTimeOffsetConverter))]
        public DateTimeOffset? Timestamp { get; set; }

        /// <summary>
        /// Status of the operation. Will be "success" if the operation completed successfully.
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }
    }
}
