name: Publish to NuGet
on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: |
        cd UsaEPay.NET
        dotnet restore
        dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        cd UsaEPay.NET.Tests
        dotnet test
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_PIN: ${{ secrets.API_PIN }}
        API_URL: ${{ secrets.API_URL }}
        RANDOM_SEED: ${{ secrets.RANDOM_SEED }}

    - name: Pack
      run: |
        cd UsaEPay.NET
        dotnet pack --configuration Release --no-restore --output nupkg /p:Version=1.0.0.${{ github.run_number }}

    - name: Push to NuGet
      run: |
        cd UsaEPay.NET
        dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
